# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true

install:
  - echo "deb http://www.unidata.ucar.edu/repos/apt i386/" | tee -a /etc/apt/sources.list
  - apt-get update
  - apt-get install udunits
  - R -e "0" --args --bootstrap-packrat
warnings_are_errors: false
